# Copyright (c) 2022-2023, Intel Corporation.
# SPDX-License-Identifier: Apache-2.0

# FPGA Bridge
CONFIG_FPGA_BRIDGE=y
CONFIG_FPGA_BRIDGE_INTEL=y
CONFIG_FPGA_BRIDGE_SHELL=y

# FPGA Manager
CONFIG_FPGA_MANAGER=y
CONFIG_FPGA_MANAGER_SHELL=y
CONFIG_FPGA_MANAGER_INTEL=y

# FPGA Freeze Controller
CONFIG_FPGA=y
CONFIG_AGILEX_FC_FPGA=y

# Misc
CONFIG_HEAP_MEM_POOL_SIZE=32768
CONFIG_SHELL_STACK_SIZE=8192

# Enable QSPI Flash
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y

# Setting the Shell prompt
CONFIG_SHELL_PROMPT_UART="agilex5$ "

# Setting the max argc
CONFIG_SHELL_ARGC_MAX=12

# Enable File System Shell
CONFIG_FILE_SYSTEM_SHELL=y

# Enable timer driver
CONFIG_COUNTER=y

# Enable Timer shell commands
CONFIG_COUNTER_SHELL=y

# Enable I2C Console
CONFIG_I2C=y
CONFIG_I2C_SHELL=y
CONFIG_I2C_SMBUS_SUPPORTED=n

# File System Setting
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y

# DMA driver
CONFIG_DMA=y
CONFIG_DMA_DW_AXI_MAX_DESC=50

# PSCI support Enable
CONFIG_PM_CPU_OPS=y
CONFIG_PM_CPU_OPS_PSCI=y

#SiP SVC Service
CONFIG_ARM_SIP_SVC_DRIVER=y
CONFIG_ARM_SIP_SVC_SUBSYS=y
CONFIG_ARM_SIP_SVC_SUBSYS_SINGLY_OPEN=y

#SiP SVC Service Shell
CONFIG_ARM_SIP_SVC_SUBSYS_SHELL=y

# EDAC options
CONFIG_EDAC_INTEL_SOCFPGA=y
CONFIG_IO96B_INTEL_SOCFPGA=y
CONFIG_SHELL_IO96B_INTEL_SOCFPGA=y
CONFIG_EDAC_ERROR_INJECT=y

# Enable SMMU
CONFIG_SMMU=y
